name: Data Processing

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      # - name: Format
      #   run: black ../../data_processing.py --line-length 88
      - name: Data Processing
        env:
          RAW_DATA_DIR: "./raw/WHR2023.csv"
        run: python ./de/data_processing.py $RAW_DATA_DIR